import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ShieldAlert, Info } from 'lucide-react';

const ACK_KEY = 'rw_disclaimer_ack_v1';

function acked(): boolean {
  try {
    return localStorage.getItem(ACK_KEY) === '1';
  } catch {
    return true; // storage blocked → don't block the app
  }
}

/** Whether the user has acknowledged the disclaimer. Tours wait on this so a
 *  first-time visitor isn't shown a coach-mark behind the disclaimer modal. */
export function disclaimerAcked(): boolean {
  return acked();
}

/** Event fired the moment the disclaimer is acknowledged, so tours can start. */
export const DISCLAIMER_ACK_EVENT = 'rw:disclaimer-ack';

/**
 * One-time, full-screen "not investment advice" acknowledgement shown on the
 * first visit (gated by localStorage). Mounted once at the app root so it covers
 * every route. Requires an explicit acknowledgement rather than a passive close.
 */
export function DisclaimerModal() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!acked()) setOpen(true);
  }, []);

  if (!open) return null;

  const dismiss = () => {
    try {
      localStorage.setItem(ACK_KEY, '1');
    } catch {
      /* ignore */
    }
    setOpen(false);
    window.dispatchEvent(new Event(DISCLAIMER_ACK_EVENT));
  };

  return (
    <div className="fixed inset-0 z-[300] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
      <div className="w-full max-w-lg glass-modal p-6 sm:p-7 animate-in fade-in zoom-in-95 duration-200">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-xl bg-amber-500/12 border border-amber-500/25 text-amber-400 shrink-0">
            <ShieldAlert size={20} />
          </div>
          <h2 className="text-lg font-semibold text-primary tracking-tight m-0">
            Not investment advice
          </h2>
        </div>

        <div className="space-y-3 text-[13.5px] text-secondary leading-relaxed">
          <p className="m-0">
            RAG Workbench is a <strong className="text-primary font-semibold">research and
            educational tool</strong> for exploring SEC filings. It is{' '}
            <strong className="text-primary font-semibold">not investment advice</strong>, not a
            recommendation, and not an offer or solicitation to buy or sell any security.
          </p>
          <p className="m-0">
            Answers are generated by AI from historical filings and may be incomplete, outdated, or
            inaccurate. Always verify against the primary source documents on EDGAR and consult a
            licensed financial professional before making any decision.
          </p>
          <p className="m-0 text-primary/90 font-medium">
            Please do your own due diligence.
          </p>
        </div>

        <button
          onClick={dismiss}
          className="mt-6 w-full py-3 rounded-xl bg-bullish hover:bg-emerald-500 text-white font-semibold text-sm border-0 cursor-pointer transition-colors active:scale-[0.99]"
        >
          I understand
        </button>
      </div>
    </div>
  );
}

/**
 * Slim, always-visible disclaimer strip for the bottom of the app shell.
 * Reinforces the modal acknowledgement on every screen.
 */
export function DisclaimerFooter({ className = '' }: { className?: string }) {
  return (
    <div
      className={`flex flex-wrap items-center justify-center gap-x-2 gap-y-1 px-3 py-1.5 text-[10px] sm:text-[11px] text-muted bg-surface/30 border-t border-border/40 ${className}`}
    >
      <span className="flex items-center gap-1.5">
        <Info size={11} className="shrink-0 text-amber-500/70" />
        <span className="text-center leading-tight">
          For research &amp; education only — <span className="text-secondary">not investment
          advice</span>. Do your own due diligence.
        </span>
      </span>
      <span className="text-border/60" aria-hidden>·</span>
      <Link to="/privacy" className="hover:text-secondary underline-offset-2 hover:underline transition-colors">
        Privacy
      </Link>
      <span className="text-border/60" aria-hidden>·</span>
      <Link to="/terms" className="hover:text-secondary underline-offset-2 hover:underline transition-colors">
        Terms
      </Link>
    </div>
  );
}
